version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t aaba-devops:${CODEBUILD_BUILD_NUMBER} -t aaba-devops:latest .
      - docker tag aaba-devops:${CODEBUILD_BUILD_NUMBER} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aaba-devops:${CODEBUILD_BUILD_NUMBER}
      - docker tag aaba-devops:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aaba-devops:latest
      #- docker build -t $IMAGE_REPO_NAME:${CODEBUILD_BUILD_NUMBER} -t $IMAGE_REPO_NAME:latest  .
      #- docker tag $IMAGE_REPO_NAME:${CODEBUILD_BUILD_NUMBER} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:${CODEBUILD_BUILD_NUMBER}
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/aaba-devops --all-tags
